### ISSUE TITLE
Example fails

### ISSUE THREAD

**Issue by james-vincent** [Gervasiolab/OpenBPMD#1]
Installed by mamba, using cuda10.1, running openbpmd.py in the examples directory with no other options given produces and error:

(base) ../../bin/openbpmd.py 
Minimizing...
Equilibrating...
/programs/x86_64-linux/openbpmd/1.0.0/lib/python3.7/site-packages/MDAnalysis/coordinates/base.py:892: UserWarning: Reader has no dt information, set to 1.0 ps
  warnings.warn("Reader has no dt information, set to 1.0 ps")
Traceback (most recent call last):
  File "../../bin/openbpmd.py", line 576, in <module>
    main(args)
  File "../../bin/openbpmd.py", line 122, in main
    args.structure, args.hill_height)
  File "../../bin/openbpmd.py", line 468, in produce
    properties)
  File "/programs/x86_64-linux/openbpmd/1.0.0/lib/python3.7/site-packages/simtk/openmm/app/simulation.py", line 105, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/programs/x86_64-linux/openbpmd/1.0.0/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 18608, in __init__
    this = _openmm.new_Context(*args)
Exception: CustomCentroidBondForce: Weights for group 0 add to 0

**Comment by dlukauskis** [comment]
This is typically what I see when the code fails to find anchor atoms. Add this line after line 439 in openbpmd.py:
```print(lig_ha_idx, anchor_atom_idx)```
What does it print?

**Comment by james-vincent** [comment]
Thanks for the quick reply. We are trying to install this for users but are not interested in making changes. We will put this on the back burner until another release is made or a fix is implemented.

Jim


James Vincent, PhD
Bioinformatics Software Curator
Dept. of BCMP, Harvard Medical School
— BioGrids.org --

**Comment by dlukauskis** [comment]
The issue has been fixed, the ligand resname in the input files was 'UNK', instead of the default 'MOL'. Latest pull request fixed that.
