### ISSUE TITLE
failed to run OpenBPMD

### ISSUE THREAD

**Issue by amarye** [Gervasiolab/OpenBPMD#5]
When I ran OpenBPMD "python openbpmd.py -s solvated.gro -p solvated.top -o ligand0_pose0 -lig_resname LIG -nreps 5", I got error .
Could you tell me how to solve it?
Thanks in advance
![Uploading Screenshot from 2023-07-17 16-27-47.png…]()

**Comment by amarye** [comment]
(openbpmd) nain1@nain1:/media/nain1/E/home/OpenBPMD/1$ python openbpmd.py -s solvated.gro -p solvated.top -o ligand0_pose0 -lig_resname LIG -nreps 5
Minimizing...
Equilibrating...
/home/nain1/anaconda3/envs/openbpmd/lib/python3.7/site-packages/MDAnalysis/coordinates/base.py:892: UserWarning: Reader has no dt information, set to 1.0 ps
  warnings.warn("Reader has no dt information, set to 1.0 ps")
Traceback (most recent call last):
  File "openbpmd.py", line 576, in <module>
    main(args)
  File "openbpmd.py", line 122, in main
    args.structure, args.hill_height)
  File "openbpmd.py", line 468, in produce
    properties)
  File "/home/nain1/anaconda3/envs/openbpmd/lib/python3.7/site-packages/simtk/openmm/app/simulation.py", line 105, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/home/nain1/anaconda3/envs/openbpmd/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 18608, in __init__
    this = _openmm.new_Context(*args)
Exception: CustomCentroidBondForce: Weights for group 0 add to 0
(openbpmd) nain1@nain1:/media/nain1/E/home/OpenBPMD/1$

**Comment by dlukauskis** [comment]
This is most likely due to missing anchor atoms, I need to add a conditional that writes a better error messege. Can you send me the input files so I can check?

**Comment by amarye** [comment]
I had used your input files in the example folder.

[Uploading solvated.zip…]()

**Comment by dlukauskis** [comment]
The resname for the ligand is 'MOL', not 'LIG'

**Comment by dlukauskis** [comment]
The last PR addresses this confusion and makes common anchor atom and lig resname errors more informative. Closing.
