### ISSUE TITLE
failed running OpenBPMD

### ISSUE THREAD

**Issue by amarye** [Gervasiolab/OpenBPMD#7]
I have ran OpenBPMD. I got error as following. Could you please tell me which version of MDAnalysis you used?

(openbpmd) nain1@nain1:/media/nain1/E/home/OpenBPMD/1$ python openbpmd.py -s solvated.gro -p solvated.top -o ligand0_pose0 -lig_resname LIG -nreps 5
Minimizing...
Equilibrating...
/home/nain1/anaconda3/envs/openbpmd/lib/python3.7/site-packages/MDAnalysis/coordinates/base.py:892: UserWarning: Reader has no dt information, set to 1.0 ps
  warnings.warn("Reader has no dt information, set to 1.0 ps")
/home/nain1/anaconda3/envs/openbpmd/lib/python3.7/site-packages/MDAnalysis/analysis/rms.py:710: DeprecationWarning: The `rmsd` attribute was deprecated in MDAnalysis 2.0.0 and will be removed in MDAnalysis 3.0.0. Please use `results.rmsd` instead.
  warnings.warn(wmsg, DeprecationWarning)
/home/nain1/anaconda3/envs/openbpmd/lib/python3.7/site-packages/MDAnalysis/analysis/contacts.py:489: DeprecationWarning: The `timeseries` attribute was deprecated in MDAnalysis 2.0.0 and will be removed in MDAnalysis 3.0.0. Please use `results.timeseries` instead
  warnings.warn(wmsg, DeprecationWarning)

**Comment by dlukauskis** [comment]
I wrote the script using the older 2.x.x version of MDA. Its seems to be giving warnings not errors. Does the code actually crash at some stage?

**Comment by amarye** [comment]
Yeah, the code gave me warning in the equilibrating stage and the code crashed after 3 hours.

**Comment by dlukauskis** [comment]
Did the script write ```results.csv``` in the output directory? Or did it crash before finishing the simulations and analysis? I just ran the example system and it ran successfully.

**Comment by amarye** [comment]
Dear
I apologize for sending this message late, but I wanted to let you know
that I have successfully used your package. Thank you very much!
